version: "3"

services:
  mysql:
    image: "mysql:5.7"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_DATABASE: test

  img-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/img-server
    environment:
      DENO_ENV: production
      APP_PORT: 8000
      APP_MAXFILESIZE: 20971520
      APP_IMGROOT: ./img
      APP_IMGFIELD: multiple
      APP_STATICROOT: ./public
      JWT_KEY: mysecret
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_DATABASE: test
      MYSQL_POOLSIZE: 10
